cat > pipeline.auto.tfvars <<EOF
project_id="bibliotech-451801" 
region="us-central1" 
zone="us-central1-a" 
instance_name="bibliotech-instance" 
repo_url="https://github.com/Ttito500/acervo-bibliotech.git" 
db_name="bibliotech" 
db_user="postgres" 
db_port="5432" 
jdbc_url="jdbc:postgresql://postgres:5432/bibliotech" 
db_schema_name="adelino_cunha" 
api_port="8090" 
email_smtp="testeacervo01@gmail.com"
db_password="admin"
senha_email_smtp="iuqr nvrk wpqb izse"
jwt_secret="briba"
EOF